# Generated by Django 3.2.22 on 2023-11-23 15:15

from django.db import migrations, models
import na.models


class Migration(migrations.Migration):

    dependencies = [
        ('na', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score_type',
            field=models.JSONField(default=na.models.default_score_type),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.JSONField(default=na.models.default_score),
        ),
    ]
