# Generated by Django 4.2.6 on 2023-10-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, upload_to='game_icons'),
        ),
    ]
