# Generated by Django 4.2.6 on 2023-10-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('na', '0003_ai_slug_game_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametag',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
