# Generated by Django 4.2.6 on 2023-11-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('na', '0005_remove_score_t_remove_score_value_game_score_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.RemoveField(
            model_name='score',
            name='player',
        ),
        migrations.RemoveField(
            model_name='score',
            name='values',
        ),
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('code', models.FileField(upload_to='evaluation_functions')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='na.game')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('min', models.IntegerField(null=True)),
                ('max', models.IntegerField(null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='na.scoretype')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='na.score')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='na.scorefieldtype')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='na.scoretype'),
            preserve_default=False,
        ),
    ]
