# Generated by Django 4.2.9 on 2024-02-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('na', '0009_playertag_unique_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_tags',
            new_name='tags',
        ),
    ]
