# Generated by Django 4.2.9 on 2024-02-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('na', '0010_rename_player_tags_player_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='na.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='na.player')),
            ],
        ),
    ]
