# Generated by Django 4.2.9 on 2024-02-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('na', '0011_rawscore'),
        ('na', '0011_userstatus'),
    ]

    operations = [
    ]
