# Generated by Django 4.2.9 on 2024-02-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('na', '0012_player_icon'),
        ('na', '0013_rename_rawscore_unprocessedresults'),
    ]

    operations = [
    ]
