# Generated by Django 4.2.9 on 2024-03-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("na", "0014_merge_20240228_1408"),
    ]

    operations = [
        migrations.AddField(
            model_name="unprocessedresults",
            name="errors",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unprocessedresults",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Not processed"),
                    (1, "Processing"),
                    (2, "Completed with errors"),
                ],
                default=0,
            ),
        ),
    ]
