# Generated by Django 4.2.9 on 2024-03-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("na", "0015_unprocessedresults_errors_unprocessedresults_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="unprocessedresults",
            name="return_code",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
